dashboard/urls.py
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('helloWorld/', views.helloWorld),
    path('search/', views.search),
    path('dashboard', views.home, name="home"),
    path('', views.home, name="home"),
]

lawyer/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('dashboard.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.conf.urls import include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('cadastro/', views.cadastro, name="cadastro"),
    path('document_upload/', views.document_upload, name="document_upload"),
    path('document_upload_user/<int:pk>', views.document_upload_user, name="document_upload_user"),
    path('documents_user/<int:pk>', views.document_user, name="document_user"),
    path('search_results', views.search_results, name="search_results"),
    path('edit_user/<int:pk>', views.UserUpdate.as_view(), name='user_edit'),
    path('delete_user/<int:pk>', views.UserDelete.as_view(), name='user_delete'),
]

dashboard/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Users(AbstractUser):
    CPF = models.CharField(max_length=11)
    Endereço = models.CharField(max_length=255)
    RG = models.CharField(max_length=9)
    Profile_picture = models.CharField(max_length=255)

class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='documents/')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(Users, on_delete=models.CASCADE)   
    def get_document_url(self):
        if self.document:
            return '/static/downloads/' + self.document.name +".pdf"

class Searches(models.Model):
    result = models.CharField(max_length=255, blank=True)
    title = models.CharField(max_length=255, blank=True)
    link = models.CharField(max_length=255, blank=True)
    user = models.ForeignKey(Users, on_delete=models.CASCADE)   

users/forms.py
from django.forms import ModelForm
from django import forms
from .models import Users, Document, Searches
class UserModelForm(forms.ModelForm):

    class Meta:
        model = Users
        fields = ['username','first_name','last_name','CPF','RG','Endereço', 'email','password']
        widgets = {
            'first_name': forms.TextInput(attrs={'class':'form-control', 'maxlength':255}),
            'last_name': forms.TextInput(attrs={'class':'form-control', 'maxlength':255}),
            'Endereço': forms.TextInput(attrs={'class':'form-control', 'maxlength':255}),
            'CPF': forms.TextInput(attrs={'class':'form-control', 'maxlength':11}),
            'RG': forms.TextInput(attrs={'class':'form-control', 'maxlength':9}),
            'username': forms.TextInput(attrs={'class':'form-control', 'maxlength':255}),
            'email': forms.TextInput(attrs={'class':'form-control', 'maxlength':255}),
            'password': forms.PasswordInput(attrs={'class':'form-control', 'maxlength':255}),
        }

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('description', 'document', 'user')
        user = forms.ModelMultipleChoiceField(queryset=Users.objects.none(), widget=forms.CheckboxSelectMultiple())
        widgets = {
            'description': forms.TextInput(attrs={'class':'form-control', 'maxlength':255}),
            'document': forms.FileInput(attrs={'class':'form-control', 'maxlength':255}),

        }

class SearchForm(forms.ModelForm):
    class Meta:
        model = Searches
        fields = ('result', 'user')
        user = forms.ModelMultipleChoiceField(queryset=Users.objects.none(), widget=forms.CheckboxSelectMultiple())
        widgets = {
            'result': forms.Textarea(attrs={'class':'form-control'}),

        }

dashboard/views.py
from django.shortcuts import render
from django.http import HttpResponse
from users.models import Users, Document
from django.contrib import messages
from django.http import HttpResponseRedirect
import urllib
from .tasks import search_task
from django.shortcuts import redirect

def helloWorld(request):
    return HttpResponse('Hello World')

def home(request):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            users = Users.objects.all()
            context = {'users':users}
            return render(request, 'dashboard/home.html', context)
        else:
            documents = Document.objects.filter(user = request.user)
            context = {'documents':documents}
            return render(request, 'dashboard/documents.html', context)
    else:
        return redirect('/accounts/login')

def search(request):
    search_task(request.POST['search'])
    messages.success(request, 'A pesquisa será feita! Agora espere os resultados!', extra_tags='alert-success')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

users/views.py
from django.shortcuts import render
from users.forms import UserModelForm, DocumentForm
from django.shortcuts import render
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.shortcuts import redirect   
from django.contrib.auth import authenticate, login
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Users, Document, Searches
from django.urls import reverse_lazy

def cadastro(request):
    form = UserModelForm(request.POST or None)
    context = {'form':form}
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('home')
    return render(request, 'users/cadastro.html', context)

class UserUpdate(UpdateView):
    model = Users
    fields = ['first_name','last_name','CPF','email','Endereço','RG']
    success_url = reverse_lazy('home')

class UserDelete(DeleteView):
    model = Users
    success_url = reverse_lazy('home')

def document_upload(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = DocumentForm()
    return render(request, 'users/documents.html', {
        'form': form
    })
def document_upload_user(request, pk):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('document_user', pk)
    else:
        form = DocumentForm()
    return render(request, 'users/documents_users_form.html', {
        'form': form,
        'pk':pk
    })
def document_user(request, pk):
    documents = Document.objects.filter(user__pk=pk)
    return render(request, 'users/documents_users.html', {
        'documents': documents,
        'user':pk
    })
def search_results(request):
    search = Searches.objects.all().order_by('-pk')
    return render(request, 'users/search_results.html', {
        'search': search
    })

dashboard/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title%}{% endblock %}</title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
            <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">
        {% block css %}
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="/">Lawyer</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                {% if user.is_superuser %}
                <li class="nav-item">
                <a class="nav-link" href="/accounts/cadastro/">Cadastrar Usuários</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/accounts/search_results">Resultados das pesquisas</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="/accounts/logout">Sair</a>
                </li>
                {% else %}

                <li class="nav-item">
                    <a class="nav-link" href="/accounts/login">Entrar</a>
                    </li>
                {%endif %}
            </ul>
            </div>
        </nav>

        {% block content %}
        {% endblock %}
    </body>
    {% block js %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</html>

dashboard/templates/dashboard/documents.html
{% extends 'base.html'%}
 
 {% block title%}
 Dashboard Admin
 {% endblock %}

    {% block content %}
     <div class="container">
       <div class="row">
         <div class="col-md-12 mt-5">
           <div class="card">
             <div class="card-header">
               Documentos
             </div>
             <div class="card-body">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th scope="col">Documento</th>
                    <th scope="col">Descrição</th>
                  </tr>
                </thead>
                <tbody>
                  {% for document in documents %}
                  <tr>
                    <th>{{document.document}}</th>
                    <th>{{document.description}}</th>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
             </div>
           </div>
         </div>
       </div>
     </div>
     
    {% endblock %}

dashboard/templates/dashboard/home.html
{% extends 'base.html'%}
 
 {% block title%}
 Dashboard Admin
 {% endblock %}

    {% block content %}

    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{ message }}
    </div>
  {% endfor %}

     <div class="container">
       <div class="row">
         <div class="col-md-12 mt-5">
           <div class="card">
             <div class="card-header">
               Usuários
               <a href="/accounts/cadastro" class="btn btn-primary float-right">
                      <i class="fa fa-user-plus" aria-hidden="true"></i> Criar novo usuário <span class="badge badge-primary"></span>
               </a>
             </div>
             <div class="card-body">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th scope="col">nome</th>
                    <th scope="col">user</th>
                    <th scope="col">email</th>
                    <th scope="col">End.</th>
                    <th scope="col">CPF</th>
                    <th scope="col">RG</th>
                    <th scope="col">editar</th>
                    <th scope="col">deletar</th>
                    <th scope="col">documentos</th>
                    <th scope="col">search</th>
                  </tr>
                </thead>
                <tbody>
                  {% for user in users %}
                  <tr>
                    <th>{{user.username}}</th>
                    <th>{{user.first_name}}</th>
                    <th>{{user.email}}</th>
                    <th>{{user.Endereço}}</th>
                    <th>{{user.CPF}}</th>
                    <th>{{user.RG}}</th>
                    <th><a href="/accounts/edit_user/{{user.id}}" class="btn btn-warning btn-sm"><i class="fas fa-edit    "></i></button></th>
                    <th><a href="/accounts/delete_user/{{user.id}}" class="btn btn-danger btn-sm"><i class="fa fa-undo" aria-hidden="true"></i></button></th>
                    <th><a href="/accounts/documents_user/{{user.id}}" class="btn btn-danger btn-sm "><i class="fas fa-file    "></i></button></th>
                    <th>
                      <form class="form-inline" method="post" action="/search/">
                        {% csrf_token %}
                        <div class="form-group mb-2">
                          <input type="hidden" name="search" class="form-control"  id="id_search" value="{{user.id}}">
                        </div>
                        <button  type="submit" class="btn btn-sm"><i class="fa fa-search" aria-hidden="true"></i></button>
                      </form>
                    </th>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
             </div>
           </div>
         </div>
       </div>
     </div>
     
    {% endblock %}

users/templates/users/cadastro.html
{% extends 'base.html'%}
 
 {% block title%}
    Cadastro de clientes
 {% endblock %}

    {% block content %}
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-8 offset-md-2">
                <div class="card auth-card">
                    <div class="card-body">
                        <h4 class="card-title text-center">Cadastro de usuario</h4>
                        <form method="post">
                            <input type="hidden" name="next" value="{{ next }}">
                            <div class="form-group">
                                    {% csrf_token %}
                                <form  class="form-signin">
                                    {{form}}
                                    <button type="submit" class="btn btn-success mt-3 center-block">Cadastrar</button>
                                </form>
                        </div>                
                    </div>
                    
                </div>
            </div>
        </div>
    {% endblock %}

users/templates/users/documents.html
{% extends 'base.html' %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.description }}
    {{ form.document }}
    {{ form.user }}
    <button type="submit">Upload</button>
  </form>

  <p><a href="{% url 'home' %}">Return to home</a></p>
{% endblock %}

users/templates/users/documents_users.html
{% extends 'base.html'%}
 
 {% block title%}
 Dashboard Admin
 {% endblock %}

    {% block content %}
     <div class="container">
       <div class="row">
         <div class="col-md-12 mt-5">
           <div class="card">
             <div class="card-header">
               Documentos
               <a href="/accounts/document_upload_user/{{user}}" class="btn btn-primary float-right">
                      <i class="fa fa-user-plus" aria-hidden="true"></i> Inserir novo documento ao usuário <span class="badge badge-primary"></span>
               </a>
             </div>
             <div class="card-body">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th scope="col">Documento</th>
                    <th scope="col">Descrição</th>
                  </tr>
                </thead>
                <tbody>
                  {% for document in documents %}
                  <tr>
                    <th>
                      <a href="../../{{MEDIA_URL}}{{document.document}}">Link</a>
                    </th>
                    <th>{{document.description}}</th>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
             </div>
           </div>
         </div>
       </div>
     </div>
     
    {% endblock %}

users/templates/users/documents_users_form.html
{% extends 'base.html' %}
 
    {% block title%}
    Dashboard Admin
    {% endblock %}
   
       {% block content %}
        <div class="container">
          <div class="row">
            <div class="col-md-12 mt-5">
              <div class="card">
                <div class="card-header">
                  Documentos
                  <a href="/accounts/document_upload_user/{{user}}" class="btn btn-primary float-right">
                         <i class="fa fa-user-plus" aria-hidden="true"></i> Inserir novo documento ao usuário <span class="badge badge-primary"></span>
                  </a>
                </div>
                <div class="card-body">
                  <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <label for="document">Documento</label>{{ form.document }}
                    <label for="description">Description</label>{{ form.description }}
                    <input type="hidden" name="user" required="" id="id_user" value="{{pk}}">
                    <button type="submit" class="btn btn-success mt-1">Upload</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
        
       {% endblock %}

users/templates/users/search_results.html
{% extends 'base.html'%}
 
 {% block title%}
 Dashboard Admin
 {% endblock %}

    {% block content %}
     <div class="container">
       <div class="row">
         <div class="col-md-12 mt-5">
           <div class="card">
             <div class="card-header">
               Resultados das buscas
             </div>
             <div class="card-body">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th scope="col">Título</th>
                    <th scope="col">Link</th>
                    <th scope="col">Usuário</th>
                  </tr>
                </thead>
                <tbody>
                  {% for s in search %}
                  <tr>
                    <th>
                        {{s.title}}
                    </th>
                    <th>
                        <a href="{{s.link}}">link</a>
                    </th>
                    <th>{{s.user}}</th>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
             </div>
           </div>
         </div>
       </div>
     </div>
     
    {% endblock %}

users/templates/users/users_confirm_delete.html
<h1>Book Delete</h1>
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

users/templates/users/users_form.html
{% extends 'base.html'%}
 
 {% block title%}
    Cadastro de clientes
 {% endblock %}

    {% block content %}
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-8 offset-md-2">
                <div class="card auth-card">
                    <div class="card-body">
                        <h4 class="card-title text-center">Editar de usuario</h4>
                        <form method="post">
                            <input type="hidden" name="next" value="{{ next }}">
                            <div class="form-group">
                                    {% csrf_token %}
                                <form  class="form-signin">
                                    {{form.as_p}}
                                    <button type="submit" class="btn btn-success mt-3 center-block">Editar</button>
                                </form>
                        </div>                
                    </div>
                    
                </div>
            </div>
        </div>
    {% endblock %}